#### Navie Bayes sınıflandırma yaparken özniteliklerin target ile arasındaki her bir durum için olasıklıklarını hesaplar. Koşullu olasılık kavramını kullanır.


* Tahmin edilecek sınıf sürekli bir değerse (reel sayılar vb..) Gaussian navie bayes kullanabilir.
* Tahmin edilecek sınıf nominal ise (çok sınıflı olabilir) Multinomial navie bayes kullanılabilir.
* Tahmin edilecek sınıf 1/0 gibi sadece ikili sınıflandırma ise Bernoulli navie bayes kullanılabilir

In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("veriler.csv")

In [3]:
from sklearn import preprocessing
le=preprocessing.LabelEncoder()

ulke=data.iloc[:,0:1].values
ohe=preprocessing.OneHotEncoder()
ulke=ohe.fit_transform(ulke).toarray()
df_ulke=pd.DataFrame(ulke,columns=['fr','tr','us'])

boy_kilo_yas=data.iloc[:,1:4].values
df=pd.DataFrame(boy_kilo_yas,columns=['boy','kilo','yas'])

frames=[df_ulke,df,data['cinsiyet']]
result = pd.concat(frames,axis=1)

In [30]:
from sklearn.model_selection import train_test_split
X=result.iloc[:,0:6].values
Y=result.iloc[:,-1].values
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.33,random_state=0)

In [43]:
# Scale
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(x_train)
X_test=sc.transform(x_test)

In [49]:
from sklearn.naive_bayes import GaussianNB,MultinomialNB,BernoulliNB
gnb=GaussianNB()
gnb2=BernoulliNB()
gnb3=MultinomialNB()

In [50]:
gnb.fit(X_train,y_train)
gnb2.fit(X_train,y_train)
gnb3.fit(x_train,y_train)

MultinomialNB()

In [51]:
y_pred=gnb.predict(X_test)
y_pred2=gnb2.predict(X_test)
y_pred3=gnb3.predict(x_test)

In [52]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm2=confusion_matrix(y_test,y_pred2)
cm3=confusion_matrix(y_test,y_pred3)

In [53]:
print('GaussianNB\n',cm),print('BernoulliNB\n',cm2),print('MultinomialNB\n',cm3)

GaussianNB
 [[0 1]
 [3 4]]
BernoulliNB
 [[0 1]
 [4 3]]
MultinomialNB
 [[0 1]
 [4 3]]


(None, None, None)